# Generated by Django 4.1.2 on 2022-11-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('empleado', models.CharField(max_length=100)),
                ('pedido', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('fecha', models.CharField(max_length=200)),
            ],
        ),
    ]
