# Generated by Django 4.1.2 on 2022-11-11 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_tiposdepizza'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TiposDePizza',
            new_name='Productos',
        ),
    ]
